### ISSUE TITLE
Is this filename correct?

### ISSUE THREAD

**Issue by ghost** [vr00n/Amazon-Web-Shenanigans#2]
https://github.com/vr00n/Amazon-Web-Shenanigans/blob/f8e40c5e118793474d74f1ff4dad14a231faeace/S3PublicBucketCheck/s3pubcheck.tf#L80

The file sitting in source dir is called "s3pubcheck.py"
While the one in this terraform code is S3PublicBucketCheck.py.zip

Is it required to create the zip file manually?  Should I create a serverless framework project to generate the zip file?

**Comment by vr00n** [comment]
Thanks @hullsean - You are correct. I just renamed the file. 

Terraform requires you to create the zip file  - https://www.terraform.io/docs/providers/aws/r/lambda_function.html

Serverless framework may do this for you automatically.

**Comment by ghost** [comment]
Ah okay.  Makes sense.  Thx!
